services:
  backend:
    image: ghcr.io/yourorg/goride-backend:latest
    ports:
      - "8001:8001"

  frontend:
    image: ghcr.io/yourorg/goride-frontend:latest
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
